### PR TITLE
New icon: Framasoft

### PR DESCRIPTION
**Pull request by Neluji**
- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** [framagenda.org](https://framagenda.org)

**Logo / icon info:** Logo is from [press kit of Framasoft](https://framasoft.org/fr/graphics/) (organisation which develops Framagenda), a bit tweaked:
- Icon used is the _Apple Touch Icon_ one, generated with FontAwesome icon _calendar-days_ at the end of the press kit page
- Both circles have been removed, and all other colors have been turned to white
- This gives us the Framasoft logo (as we have for menu in the top-right corner of the page), with the FontAwesome icon indicating the relevant service (here calendar service)

**Background color info:** From press kit page

As Framasoft provides several services, (spreadsheet, pad, map...), there may be future icons with the same pattern, just the icon representing the service changing. I don't know if it is a good idea, and I also made another version of the logo, which may be better ? :

### CODE REVIEW

**Comment by krisu5** [comment]
Sidenote: remember to add `https://` (or less common `http://`) at start of URLs, otherwise they don't work properly.

[framagenda.org](https://framagenda.org/) url (and previous PR's links) had that issue. I fixed them.

**Comment by krisu5** [comment]
This whole Frama service thing is kinda a mess, but I rather have one icon for just Framasoft. I don't want scenario where we need 10+ Frama-related icons that are basically hosted in one place, even if they all have different login system.

The logo modification isn't official, so it's not good enough.

**Review by krisu5 — CHANGES_REQUESTED** [review]
1. Remove the calendar icon (and center the Framasoft logo etc.)
2. Rename the icon as `Framasoft.svg`

**Comment by Neluji** [comment]
> This whole Frama service thing is kinda a mess, but I rather have one icon for just Framasoft. I don't want scenario where we need 10+ Frama-related icons that are basically hosted in one place, even if they all have different login system.

Yes indeed, I was a bit... astonished to see that each service has its own login system 😓 

> The logo modification isn't official, so it's not good enough.

Ok, good to know for future contrib (even though I think I should already know it ^^')

**Comment by krisu5** [comment]
No problem! Adding this to the repo 👍

**Pull request merged**
