### PR TITLE
Made the Toontown Rewritten icons more accurate to the logo and websi…

### PR DESCRIPTION
**Pull request by joshcancode**
…te's color palette

Also compressed the PNG icons to identical file sizes as the old icons

- [x] I have read and followed CONTRIBUTING document.
- [x] I only added SVG(s) to the pull request.
- URL of the site or app **(required, unless it's generic icon):** https://www.toontownrewritten.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://www.toontownrewritten.com/

### CODE REVIEW

**Comment by joshcancode** [comment]
I know the contribution document states to only upload SVG files, I will remove the PNG files if need be.

**Comment by krisu5** [comment]
I'm okay with edits, but these icons weren't edit according to the guidelines. I made changes based of guidelines.

**Comment by joshcancode** [comment]
> 
> 
> I'm okay with edits, but these icons weren't edit according to the guidelines. I made changes based of guidelines.

Sorry about that. I re-read the guidelines and the only thing I seem to have missed was the SVG compression site, I didn't see any color guidelines that I didn't follow. The white in the eyes is part of the logo, and the outlines are black according to the Press Kit. If I'm misunderstanding anything please let me know for future contributions!

**Comment by krisu5** [comment]
> The white in the eyes is part of the logo, and the outlines are black according to the Press Kit.

The most important thing when making icons for aegis-icons is that logo only has one color (`#FFFFFF`), making it monochrome.

Also `fg.var` icon is not needed anymore, because of darker bg color (I usually make `fg.var` when icon uses bright colors like yellow).

Missing the SVG compression is not big issue, I can do that afterwards if needed.

**Comment by joshcancode** [comment]
> 
> 
> The most important thing when making icons for aegis-icons is that logo only has one color (`#FFFFFF`), making it monochrome.
Got it, I thought that it had to have a foreground color of white and could have other basic colors in it, thank you for clarifying!

**Pull request merged**
