### PR TITLE
New icon: Thunderpick

### PR DESCRIPTION
**Pull request by joshcancode**
**URL of the site:**
> [thunderpick.io](https://thunderpick.io/)

**Proof of the Aegis-compatible 2FA:**
> https://thunderpick.io/blog/stay-safe-with-2fa-authentication

**Logo / icon info:**
> SVG logo from main page

**Background color info:**
> From [favicon's](https://thunderpick.io//icon/favicon-192x192.png) background color: `#171a21`

- [X] I have carefully read and followed CONTRIBUTING document.

### CODE REVIEW

**Review by krisu5 — CHANGES_REQUESTED** [review]
Use logo SVG's blue color instead.

**Comment by krisu5** [comment]
_Sidenote:_ I understand need to save time with copy-pasting PR template from your previous PRs, but I don't recommend it because of possible new PR template additions like "Proof of the Aegis-compatible 2FA".

**Comment by joshcancode** [comment]
> _Sidenote:_ I understand need to save time with copy-pasting PR template from your previous PRs, but I don't recommend it because of possible new PR template additions like "Proof of the Aegis-compatible 2FA".

No problem, I won't copy-paste previous PR's anymore, however the original PR does have the proof of 2FA linked https://thunderpick.io/blog/stay-safe-with-2fa-authentication

**Review by krisu5 — CHANGES_REQUESTED** [review]
I think you misunderstood: I meant use the logo's blue color as BG 😅

**Comment by krisu5** [comment]
> > _Sidenote:_ I understand need to save time with copy-pasting PR template from your previous PRs, but I don't recommend it because of possible new PR template additions like "Proof of the Aegis-compatible 2FA".
> 
> No problem, I won't copy-paste previous PR's anymore, however the original PR does have the proof of 2FA linked https://thunderpick.io/blog/stay-safe-with-2fa-authentication

Yes, I noticed it was included. I don't know if there's still gonna be PR template updates, but just as heads up ;)

**Comment by joshcancode** [comment]
> I think you misunderstood: I meant use the logo's blue color as BG 😅

Yeah haha I fixed it afterwards, I edited it in the browser. The latest update should be all good!

**Review by krisu5 — CHANGES_REQUESTED** [review]
Sorry to bother you once again, but I noticed that this logo design is too wide and narrow for our icons, hence makes it too hard to see / read on device. Like contributing doc states, the next move is make it more like favicon's design, meaning only thunder should be on the icon.

I can do it by myself later if you want, but currently sick + Christmas, so it takes awhile.

EDIT: I had time and energy to do this by myself.

**Review by krisu5 — APPROVED** [review]

**Pull request merged**
