### PR TITLE
Add STACK icon

### PR DESCRIPTION
**Pull request by bartlibert**
- [x] I have read and followed CONTRIBUTING document.
- [x] I only added SVG(s) to the pull request.
- URL of the site or app: https://www.transip.nl/stack
- Where did you took the BG color(s): https://www.transip.nl/img/cms/stack-comparison-stack.svg

### CODE REVIEW

**Comment by krisu5** [comment]
Does it use own login system or do you use TransIP account to login with? If latter, I have to reject this one since there already is TransIP icon for this purpose...

EDIT: I assume you need a different account details then TransIP account based of this: https://www.transip.nl/knowledgebase/artikel/453-inloggen-op-stack/ (what I understanded with machine translation)

I just want confirmation.

**Comment by bartlibert** [comment]
It is indeed a separate account. You actually access the storage via \<username\>.stackstorage.com and use a dedicated login there. You don't need to be a transip hosting customer to use it. But if you just use stackstorage.com as the url, it redirects to the transip site.

**Review by krisu5 — CHANGES_REQUESTED** [review]
1. Logo is way too big! Use template file and keep the logo size inside of the guides, do not cross the min guides (left and right guide closer to center).
2. Logo should include the circle part (see: https://www.transip.nl/img/cms/stack/new/10tb4.png)
3. Try making SVG markup like this: https://github.com/aegis-icons/aegis-icons/blob/master/SVG/1Password.svg?short_path=7d464e5
4. Filename should be uppercased as brand intended (I made a commit change for this already, but just in case if you didn't notice that)

**Comment by krisu5** [comment]
> It is indeed a separate account. You actually access the storage via <username>.stackstorage.com and use a dedicated login there. You don't need to be a transip hosting customer to use it. But if you just use stackstorage.com as the url, it redirects to the transip site.

Okay, then I can accept this icon after changes have been made 🙂

**Review by krisu5 — APPROVED** [review]
Perfect! 👍

EDIT: well, almost. 😅 I made few markup fixes.

**Pull request merged**
