### PR TITLE
New icon: Exaroton

### PR DESCRIPTION
**Pull request by yfunk**
**URL of the site:**

https://exaroton.com

**Logo / icon info:**

Extracted logo with SVG Gobbler from main page (https://exaroton.com)

Exaroton is the paid hosting service by Aternos, which already have an icon in this pack. However, [unlike their parent company](https://aternos.gmbh/en/branding), Exaroton don't seem to have an official style guide so I had to extract the logo and color from their website.

**Background color info:**

Background color `#19ba19` is from the logo.
      
**Illustrator files** _(if you have any):_

[Exaroton.zip](https://github.com/aegis-icons/aegis-icons/files/8418650/Exaroton.zip)

- [x] I have carefully read and followed CONTRIBUTING document.

align

I made the logo a bit bigger than in similar icons (e.g. Netlify, BlockFi, Binance), because the indented corners make this one look more rounded and it seemed too small next to other round icons.

Feel free to suggest or make changes 🙂

### CODE REVIEW

**Comment by yfunk** [comment]
@krisu5 Should PRs also update the `pack.json` and `pack_TEMPLATE.json` files? I noticed you always have to do that yourself after merging.

I tried running `pack.py gen-def`, but it replaced all the `category` fields with `null`. Are the changes just manual (at the right place in alphabetic order) and what is the difference between the two JSON files?

**Comment by krisu5** [comment]
> @krisu5 Should PRs also update the `pack.json` and `pack_TEMPLATE.json` files? I noticed you always have to do that yourself after merging.

No, I do those personally.

**Comment by krisu5** [comment]
Added to the repo.

> Are the changes just manual (at the right place in alphabetic order) and what is the difference between the two JSON files?

Changes are made manually with Notepad++ and "Compare" plugin.

First I re-generate `pack.json`, then [I launch new Notepad++ window for `pack.json` and `pack_TEMPLATE.json`](https://github.com/aegis-icons/aegis-icons/blob/master/_compress/.3_icon_pack_helper.bat#L49), activate "Compare" plugin, find the new entries from `pack.json` and paste them to `pack_TEMPLATE.json` (based of order of `pack.json`). Change the `category` values from null to something else. Then copy all of content of `pack_TEMPLATE.json` and paste that back to `pack.json`. [Then test that JSONs are correctly done and generates the pack](https://github.com/aegis-icons/aegis-icons/blob/master/_compress/.3_icon_pack_helper.bat#L55).

There's the explanation of the process. It's not most elegant solution, so that's why it's not documented and why I'm only one allowed to do those things.

**Comment by yfunk** [comment]
> There's the explanation of the process. It's not most elegant solution, so that's why it's not documented and why I'm only one allowed to do those things.

Thanks for explaining 🙂

Makes sense that only you do this if the process has this much manual labor and therefore potential for small mistakes.

**Pull request merged**
