### PR TITLE
New icon: Cryptohopper

### PR DESCRIPTION
**Pull request by joshcancode**
- [X] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** [cryptohopper.com](https://cryptohopper.com/)

**Proof of the Aegis-compatible 2FA:** https://docs.cryptohopper.com/docs/user-profile/two-factor-authentication-2fa/

**Logo / icon info:** https://www.cryptohopper.com/about/press

**Background color info:** Background color is from the logo (`#00B2C8`)

The site's logo was way too wide, but this is their main logo and favicon so I had to work with it despite it being literally just a circle. If there's any ideas to make this look better, I'm all for it.

### CODE REVIEW

**Comment by krisu5** [comment]
Just for heads up, please check up first for the press page before taking logo from header (as already instructed on the CONTRIBUTING), since [Cryptohopper has one](https://www.cryptohopper.com/about/press) with logos and everything.

These can have important information about logo usage, colors ect.

**Comment by krisu5** [comment]
I rather have *logo / icon info* URL to press page, if it has assets and/or info about logos: https://www.cryptohopper.com/about/press

**Comment by joshcancode** [comment]
> I rather have *logo / icon info* URL to press page, if it has assets and/or info about logos: https://www.cryptohopper.com/about/press

I actually had no idea there was a press page, my bad.

**Comment by krisu5** [comment]
> > I rather have _logo / icon info_ URL to press page, if it has assets and/or info about logos: https://www.cryptohopper.com/about/press
> 
> I actually had no idea there was a press page, my bad.

Link is usually at the bottom of the page if there's one, that's the first thing I look before anything else. Then I check the top navigation.

Also I recommend using icon grid (can be found from "_templates" dir), I haven't written the documentation yet for it, but it has the now standard size for 1:1 circle / square logos.

**Comment by joshcancode** [comment]
> > > I rather have _logo / icon info_ URL to press page, if it has assets and/or info about logos: https://www.cryptohopper.com/about/press
> > 
> > I actually had no idea there was a press page, my bad.
> 
> Link is usually at the bottom of the page if there's one, that's the first thing I look before anything else. Then I check the top navigation.
> 
> Also I recommend using icon grid (can be found from "_templates" dir), I haven't written the documentation yet for it, but it has the now standard size for 1:1 circle / square logos.

Okay I'll use that from now on!

**Pull request merged**
