### PR TITLE
New icon: Passmulticadeaux

### PR DESCRIPTION
**Pull request by Dampypena**
- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:**
https://www.passmulticadeaux.fr/

**Proof of the Aegis-compatible 2FA:**

PassMultiCadeauOTP

**Logo / icon info:**
I retrieved the [logo](https://play-lh.googleusercontent.com/xNU7nxNW6ThQkA7JdPEAtYom0lIzBMLJ-C_bCZHJ46tBg-WnwarSEwX7_410Ac9DiVw=w240-h480) from the [google play application](https://play.google.com/store/apps/details?id=fr.passmulticadeaux.www.pwa&gl=FR). I converted it in SVG using [Convertio](https://convertio.co/png-svg/).

**Background color info:**
The color was extracted from the footer of the [website](https://www.passmulticadeaux.fr/) `#74195a`

image

### CODE REVIEW

**Review by krisu5 — CHANGES_REQUESTED** [review]
It's unclear what's the actual spelling of the name, but I changed it to `Passmulticadeaux` instead based of Google Play Store page (usually I don't use that as source, but this time I had limited options).

> The color was extracted from the footer of the [website](https://www.passmulticadeaux.fr/) #74195a

Use one of the colors of the logo (preferably violet, since its most used color on that logo).

> I converted it in SVG using [Convertio](https://convertio.co/png-svg/).

This tool's image tracing is mediocre, **don't use it**. I have tested many of the image tracing tools and don't recommend most of them.

If you **have to** use image trace (please search for vector logos first, don't use it as first option), use [Vectorizer.io with mentioned instructions here](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images) (at end of the "Finding source images" section).

---

I added info to CONTRIBUTING about not using other image tracers except the currently recommended ones.

**Comment by Dampypena** [comment]
I changed the color to `#8139aa`, the violet from the logo.

**Review by krisu5 — DISMISSED** [review]
Thanks, but logo is still the one that was made with unacceptable image tracing tool.

Please recreate the logo from image with [one of the tools here](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#image-tracing-tools).

**Comment by Dampypena** [comment]
I changed the logo by using Vectorizer.io. Tell me if it needs to be modified. I'm using Inkscape.

**Comment by krisu5** [comment]
TBH, it was even worse for some reason, I guess Vectorizer.io isn't good at small images. Vector Magic (and Vectorizer.AI) are better at that.

I fixed it myself with Vector Magic and manually fixing the some parts.

See the difference: [before (your last revision)](https://raw.githubusercontent.com/aegis-icons/aegis-icons/8cb3ffb3361dbc09b924c49e54800b2aef6ac08a/icons/1_Primary/Passmulticadeaux.svg) and [after](https://raw.githubusercontent.com/aegis-icons/aegis-icons/16e5f6b0f893e408e09d729ff3d6c97e5adf3672/icons/1_Primary/Passmulticadeaux.svg). Less janky lines and file size is also over 60% smaller because of changes.

**Pull request merged**
