### PR TITLE
New icon: Del-One Federal Credit Union

### PR DESCRIPTION
**Pull request by joshcancode**
**URL of the site:**
> [del-one.org](https://www.del-one.org/)

**Logo / icon info:**
> Created graphic from scratch following the logo from [BrandFetch](https://brandfetch.com/del-one.org)

**Background color info:**
> Background color is from the logo. `#00c4b2`

- [X] I have carefully read and followed CONTRIBUTING document.

### CODE REVIEW

**Comment by joshcancode** [comment]
Hey krisu5, sorry to re-open the pull request but I couldn't find another way to contact you. What AI do you use to compress the SVG, so I can do it before I commit?

**Comment by krisu5** [comment]
Adobe Illustrator CC 2017, any CC version is okay.

I don't know why Inkscape (IIRC is the software you use) is still so much behind making optimized vectors compared to AI.

I tested with slightly different set of optimized SVG saving settings today in Inkscape but nothing compares to AI.

**Comment by joshcancode** [comment]
Alright thank you! I'll go ahead and grab that. Yeah I use Inkscape, it is a bit annoying with it not being good for simplification/compression. I manually removed and simplified as many nodes as possible, and the compressed version you created is the exact same in terms of node placement so I'm not sure what Inkscape is missing in that regard.

**Comment by krisu5** [comment]
Small correction what I said: any CC version that is 2017 **and after** are fine.

In 2017, they added "Export to Screens" saving option and that's what I'm using all the time.

**Pull request merged**
