### PR TITLE
New icon: Line 6

### PR DESCRIPTION
**Pull request by hispanasian**
- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** [https://line6.com/](https://line6.com/)

**Proof of the Aegis-compatible 2FA:**
No publicly available documentation available. 2fa can be set up for Line 6 accounts at [https://line6.com/account/2fa/](https://line6.com/account/2fa/).

Screenshot 2023-02-05 234540

**Logo / icon info:** [Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Line6_Logo.svg/800px-Line6_Logo.svg.png?20140903221444) taken from [https://commons.wikimedia.org/wiki/File:Line6_Logo.svg](https://commons.wikimedia.org/wiki/File:Line6_Logo.svg) which clearly matches logo found on the official site: [https://line6.com/](https://line6.com/).

*Maintainer note:* https://line6.com/company/press-photos/ (press kit at bottom, only PNGs)

**Background color info:**
Primary: Background color is from the [logo](https://line6.com/data/6/0a020a3e871559ea2aec0f8fc/file/zip/line-6-logos.zip) (`#000000`).
Variation: Background color is from the font on the social and links at the bottom of the [website](https://line6.com/) (`#999999`) .

### CODE REVIEW

**Review by krisu5 — CHANGES_REQUESTED** [review]
[Take the BG color from the logo](https://line6.com/data/6/0a020a3e871559ea2aec0f8fc/file/zip/line-6-logos.zip) (press kit link), it's not acceptable to use background color from website unless logo is full white and no other versions aren't available.

And create `bg.var` version also, if you use dark color from primary icon.

**Comment by hispanasian** [comment]
> [Take the BG color from the logo](https://line6.com/data/6/0a020a3e871559ea2aec0f8fc/file/zip/line-6-logos.zip) (press kit link), it's not acceptable to use background color from website unless logo is full white and no other versions aren't available.
> 
> And create `bg.var` version also, if you use dark color from primary icon.

Got it. Thanks for the press kit! I avoided `#000000` as the background as I thought it was illegal according to [./_templates/z_bg-colors_to_avoid.svg](https://github.com/aegis-icons/aegis-icons/blob/master/_templates/z_bg-colors_to_avoid.svg). Thanks for the clarification here!

I ended up creating a `fg.bg.var` from the second icon in the press kit. I'm not sure how to articulate the variation in the PR message but I hope it's clear.

**Review by krisu5 — CHANGES_REQUESTED** [review]
You are misunderstanding point of variation icons.

Please read this: https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#bgvar-fgvar--fgbgvar-icons

The primary icon is OK, but the `fg.bg.var` icon is all wrong and shouldn't be here in this commit.

You want to make `bg.var` icon with totally different BG color and **not** change the logo color from `#fff` to something else. **`fg.bg.var` icons are only made when absolutely necessary**, it's for edge cases. For example, if only reasonable color you found for `bg.var` is light grey, you should then make `fg.bg.var` icon **too**, since it can make white logo too hard to see for some screens / people.

Please see the examples in the CONTRIBUTING doc and please follow CONTRIBUTING doc more carefully in general. CONTRIBUTING doc answers most of your questions.

**Comment by hispanasian** [comment]
> You are misunderstanding point of variation icons.
> 
> Please read this: https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#bgvar-fgvar--fgbgvar-icons
> 
> The primary icon is OK, but the `fg.bg.var` icon is all wrong and shouldn't be here in this commit.
> 
> You want to make `bg.var` icon with totally different BG color and **not** change the logo color from `#fff` to something else. **`fg.bg.var` icons are only made when absolutely necessary**, it's for edge cases. For example, if only reasonable color you found for `bg.var` is light grey, you should then make `fg.bg.var` icon **too**, since it can make white logo too hard to see for some screens / people.
> 
> Please see the examples in the CONTRIBUTING doc and please follow CONTRIBUTING doc more carefully in general. CONTRIBUTING doc answers most of your questions.

Apologies for the many mistakes. It was never my intention to make things difficult for you and it's 100% my bad for not paying closer attention to the docs. Many thanks for your patience and guidance on this and the prior PR.

**Comment by hispanasian** [comment]
Some elaboration on bg color choice:

The [press kit](https://line6.com/data/6/0a020a3e871559ea2aec0f8fc/file/zip/line-6-logos.zip) has two logos which use the colors `#ffffff`, `#000000`, `#1a1a1a` and `#d9dadb` which I believe are either too close to `#000000` or too light to see with a `#ffffff` foreground. The [website](https://line6.com/) itself uses a color palette  of `#000000`, `#ffffff`, and various shades of gray. I think `#999999` should achieve the CONTRIBUTING.md guideline of creating a bg variation for use on a dark / AMOLED theme.

**Review by krisu5 — APPROVED** [review]
I accept the `bg.var` icon.

I forgot to mention that for variation icons, it's then okay to use color from website (unless brand has guidelines and dedicated color palette).

In a nutshell:
- For primary icon, always use color from brand guidelines or from logo, if possible.
- For variation icons, restrictions are more loose.

**Pull request merged**
