### PR TITLE
Nvidia Icon

### PR DESCRIPTION
**Pull request by sreeragag7**
- [x] I have read and followed CONTRIBUTING document.
- [x] I only added SVG(s) and PNG(s) to pull request.
- https://www.nvidia.com/

Illustrator files (if you have any):
[Nvidia.zip](https://github.com/aegis-icons/aegis-icons/files/5923970/Nvidia.zip)

### CODE REVIEW

**Comment by krisu5** [comment]
Compression method (or how you save the PNG) creates artifacts to png.

I fixed the PNG you sended, you don't have to do anything.

What compression you're using if I may ask? ☺ If it's one of the methods I have listed to CONTRIBUTING, I have to remove it from it then.

- [Here's your PNG zoomed in, that has compression artifacts created to the edges](https://user-images.githubusercontent.com/3540275/106910369-d45a8200-6709-11eb-8ec0-d87f7df875e8.png)
- And [here's mine without](https://user-images.githubusercontent.com/3540275/106910466-ec320600-6709-11eb-82b0-28ccb119a8d3.png)

Notice how edges has dark greenish "shadows" in it, that's the artifact.

In the future, I recommend saving PNG as is (no "save to web" or anything like that, "export for screens" is okay) and if you're Windows user, [I recommended Pingo's GUI "Pinga"](https://www.css-ig.net/pingo). Pinga shouldn't make artifacts, if it's in "lossless" setting. Rest of the info is in the [CONTRIBUTING doc](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#png-compression).

Everything else was OK.

**Comment by krisu5** [comment]
I also noticed minor artifacts plus other weirdness in the previous icons you sended. I'm fixing those ASAP.

**Comment by sreeragag7** [comment]
Sorry about that. I used Pinga in the lossless setting but the png still had a big size. So I used a tool called "Pngyu" which reduced the size but may have introduced these  artifacts.

**Comment by krisu5** [comment]
> Sorry about that. I used Pinga in the lossless setting but the png still had a big size.

[I think you forgot "extreme" setting](https://user-images.githubusercontent.com/3540275/80963782-52ef5f80-8e18-11ea-8dbe-fc1c58fa81e4.png).

With that, it goes from 29,8 kb to 10,5 kb. If it doesn't for some reason compress that much, [reinstall it with latest version](https://css-ig.net/pingo).

**Pull request merged**
