### PR TITLE
New icon: PulseHeberg

### PR DESCRIPTION
**Pull request by Paragoumba**
- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** https://pulseheberg.com

**Proof of the Aegis-compatible 2FA:**
image

**Logo / icon info:**
Extracted the svg logo from this page: https://pulseheberg.com

**Background color info:**
Background color is from the logo (`#8a40ffff`).

### CODE REVIEW

**Comment by krisu5** [comment]
Please show all the options for the 2FA, current screenshot doesn't tell me that this has TOTP 2FA (there can be several different options for 2FA or no TOTP at all) and I couldn't find the answer from Google.

**Review by krisu5 — CHANGES_REQUESTED** [review]
Logo is too big, fit it inside of the top and bottom guides.

**Comment by Paragoumba** [comment]
There doesn't seem to be any documentation or any place in the dashboard that mentions TOTP. I might disable it and re-enroll, but I'd prefer not to, if possible. Would a screenshot of Authy with the PulseHeberg entry suffice?

**Review by krisu5 — APPROVED** [review]

**Comment by krisu5** [comment]
Well okay, I believe you. I don't want to make this too complicated then.

Merging this.

**Pull request merged**
