### PR TITLE
New icon: KACE

### PR DESCRIPTION
**Pull request by IgorAngelini**
Add an icon for the Quest KACE appliances

- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site: https://www.quest.com/kace/**

**Proof of the Aegis-compatible 2FA:**

https://support.quest.com/technical-documents/kace-systems-management-appliance/11.1%20common%20documents/administrator-guide/73#TOPIC-1610972

**Logo / icon info:**

Logo was taken from wikimedia on https://upload.wikimedia.org/wikipedia/commons/2/20/KACE_logo.svg

I used Inkscape to make the logo from the template file. 

SVG was then run through SVGOMG with the "Prettify markup" option as instructed.

**Background color info:**

The color was taken from the original wikimedia logo and is the standard Quest strong orange hue. #f05223

The Quest KACE System Management Appliance (SMA) has the option for 2FA. I recently moved to Aegis and saw there wasn't any KACE related icons in the icon pack, so instead of just making one for my personal use, I thought of contributing to the repo.

### CODE REVIEW

**Comment by krisu5** [comment]
Sorry, but I don't fully understand what this product does, so you have to answer this.

Do you need to login to use the system via [Quest](https://www.quest.com) site's "sign in" button or is this hostable software?

If it's former, then this submission isn't acceptable because KACE would use Quest account system, therefore Quest icon is needed rather then KACE.

> SVG was then run through SVGOMG with the "Prettify markup" option as instructed.

This itself isn't enough, read rest of the instructions in that section.

**Review by krisu5 — CHANGES_REQUESTED** [review]
- [Do rest of the tasks from the "SVG compression & cleanup" section](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression--cleanup) (correct SVG formatting and cleanup)
- Circles are part of the logo, please include them. Make a hole with "K" to the circle.

**Comment by IgorAngelini** [comment]
It's a hostable software for endpoint management, it's not used to log in to Quest's website.

I'll be addressing the .svg formatting shortly, sorry for not reading the documentation fully.

**Comment by krisu5** [comment]
I edited another thing, just FYI: circles are part of the logo, please include them. Make a hole with "K" to the circle.

**Review by krisu5 — CHANGES_REQUESTED** [review]
Circles are part of the logo, please include them. Make a hole with "K" to the circle.

**Review by krisu5 — CHANGES_REQUESTED** [review]
Still not correct, make it exactly like in the logo, but "K" and inner circle creates a hole (example tutorial: https://logosbynick.com/cut-a-hole-in-an-object-with-inkscape/), then make it white.

Also, [only single path](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#vectors) should be there and again, SVG formatting / cleanup.

**Comment by IgorAngelini** [comment]
Ok, so the logo should be in one single path.

Just clarify, the K and the circle were taken from the original logo. I don't understand what you want me to make a hole into.

Should I break the guides and bring the inner circle closer to the border as original?
Should I cut the outer circle with the inner and make a transparent hole encircling the K?
Are you looking for something like this?:
image


Could you be more specific?

Modified on the left, original on the right.
image

For now, I'll just commit the formatting.

**Comment by krisu5** [comment]
Top one is almost correct, but not quite. I mean like this:

Clipboard02

I just selected all the elements in that "K" logomark from [the vector](https://upload.wikimedia.org/wikipedia/commons/2/20/KACE_logo.svg) and subtracted the paths.

Point is that no element from the logo is removed on the process, we want it close as possible to original in monochromic white form.

**Review by krisu5 — APPROVED** [review]

**Pull request merged**
