### PR TITLE
Add rubygems.org icon

### PR DESCRIPTION
**Pull request by ixti**
- [x] I have read and followed CONTRIBUTING document.
- [x] I only added SVG(s) to the pull request.
- URL of the site or app **(required, unless it's generic icon):** https://rubygems.org 
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://rubygems.org/pages/about

### CODE REVIEW

**Comment by krisu5** [comment]
Icon is good but needs couple of things:
1. [Make logo vector into single compound path](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#vectors)
2. I assume you're using Inkscape, so please [save the SVG as plain, **not as Inkscape SVG**](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#save-and-export)
2. And [compress the SVG](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression)

**Comment by ixti** [comment]
@krisu5 Thanks for the details guide. ~I don't know how to proceed with first step though. When I try to make "union" it makes icon disappear :((~

UPDATE: I've misunderstood. I have to make a union of logo object.

**Comment by ixti** [comment]
@krisu5 Done!

**Comment by ixti** [comment]
@krisu5 Should I add changes to pack_*.json?
Issuer: rubygems.org

**Comment by krisu5** [comment]
No need to, that's my job.

I made slightly changes to the SVG code, because SVG compression didn't delete all the unnecessary stuff.

Also renamed the icon to more correct format.

**Comment by ixti** [comment]
Awesome. Thank you.

**Pull request merged**
