### PR TITLE
New icon: ING (Internationale Nederlanden Groep)

### PR DESCRIPTION
**Pull request by dan-danache**
- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** https://developer.ing.com/

**Proof of the Aegis-compatible 2FA:** https://developer.ing.com/openbanking/contact/support (FAQ has a "Second Factor Authentication" section)

**Logo / icon info:** Extracted logo with SVG Gobbler from https://developer.ing.com/

**Background color info:** `#ff6200`

> **Maintainer note:** Official brand guidelines / logo resources page: https://www.ing.be/en/individuals/services/ing-corporate-logo. Since the site is effing slow, here's direct URL to **Logo guidelines PDF**: https://assets.ing.com/m/a8316ae4a3e95434/LogoGuidelines.pdf

### CODE REVIEW

**Comment by krisu5** [comment]
Rejected, breaks [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) guidelines majorly (not using icon template etc.) and "[icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#not-approved)":

> - :warning: **Only for icon submissions:** submitting unmodified SVGs / [raster images](https://simple.wikipedia.org/wiki/Raster_graphics) from the web.
>   - You'll need to design the icon **yourself** for submissions!

**Comment by dan-danache** [comment]
Hi @krisu5, sorry for the bad PR; my bad!

I'm now working on a compliant icon version but have trouble creating something that looks good especially when scaling down (see icon versions in the bottom rows). Quick question: would it be acceptable to go beyond the template outer-guidelines as shown in the screenshot below?

Screenshot 2023-06-16 at 13 57 49

**Comment by krisu5** [comment]
> Quick question: would it be acceptable to go beyond the template outer-guidelines

No, it's prohibited on the [CONTRIBUTING guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#layout) *(stay inside of the guides as much as possible.)* and [icon grid](https://github.com/aegis-icons/aegis-icons/blob/master/_templates/z_icon_grid.svg).

The icon on last row & center column is acceptable. Use icon grid to properly size and center the logo to the icon (add icon grid as top layer in vector designing software, remove it after finishing).

And **please** read the CONTRIBUTING as closely and carefully as possible!

**Review by krisu5 — CHANGES_REQUESTED** [review]
Logo is too big, scale it to icon grid's 1:1 square size (480 x 480 px).

**Review by krisu5 — DISMISSED** [review]
Logo still isn't 480 x 480 px sized. Use numerical size changer to make it exactly those sizes (in Inkscape for example, it's the `W:` & `H:` boxes on top toolbar when vector is activated). Visually in the icon grid, it's inside of green / black dashed stroke square.

**Pull request merged**
