### PR TITLE
New icon: Trality

### PR DESCRIPTION
**Pull request by joshcancode**
**URL of the site:**
> [trality.com](https://www.trality.com/)

**Proof of the Aegis-compatible 2FA:**
> https://trality.zendesk.com/hc/en-us/articles/360020852480-Setting-up-Multi-Factor-Authentication-MFA-

**Logo / icon info:**
> Image traced from [main logo](https://app.trality.com/assets/9d690e23c373835198da60e831c2525e.png)

**Background color info:**
> From site's main color named "Chakra", without transparency the color is `#8dc2ed`

- [X] I have carefully read and followed CONTRIBUTING document.

<!-- ▲▲▲ REQUIRED!
Confirm that you have done these things.
Replace space with x inside of the brackets: [ ] ➜ [x]

After this line, you can now comment freely. Thank you for contributing and following the instructions :) --

Logo was slightly moved down to appear centered. I optimized every node of this SVG by hand, so hopefully you won't have to do much work @krisu5 😂

### CODE REVIEW

**Comment by krisu5** [comment]
Merging. 👍

**Comment by joshcancode** [comment]
> Merging. 👍

May I ask what "tabulation" is referring to here? I also don't see a difference in the size of the image, it looks like the width was reduced by 2px and decimals are longer.

**Comment by krisu5** [comment]
Sorry, I meant indentation. It's related to SVG code, not vector itself.

You have 2 space indentations instead of 3 that we use (it's the spaces before `<` characters). See https://github.com/aegis-icons/aegis-icons/pull/780/commits/0305766160fa25ea89aa328963c15df86f877939 by clicking `<>` button.

From CONTRIBUTING doc, Checklist for SVG formatting:
> Check that the **indentation is 3 spaces** (important if you used SVGOMG).

**Comment by joshcancode** [comment]
> Sorry, I meant indentation. It's related to SVG code, not vector itself.
> 
> You have 2 space indentations instead of 3 that we use (it's the spaces before `<` characters). See [0305766](https://github.com/aegis-icons/aegis-icons/commit/0305766160fa25ea89aa328963c15df86f877939) by clicking `<>` button.
> 
> From CONTRIBUTING doc, Checklist for SVG formatting:
> 
> > Check that the **indentation is 3 spaces** (important if you used SVGOMG).

Ah okay, yeah my bad I had made this at work. Thanks for the clarification!

**Pull request merged**
